CREATE TABLE SCOTT.FS_MENU
(
  FSM_CODE     NUMBER(4)                        NOT NULL,
  FSM_NAME     VARCHAR2(50 BYTE),
  FSM_PRICE    VARCHAR2(50 BYTE),
  FSM_PICTURE  VARCHAR2(100 BYTE),
  FSM_GOOD     NUMBER(10),
  FSM_BAD      NUMBER(10)
)

ALTER TABLE SCOTT.FS_MENU ADD (
  CONSTRAINT XPKFS_MENU
  PRIMARY KEY
  (FSM_CODE)
  USING INDEX SCOTT.XPKFS_MENU
  ENABLE VALIDATE);

--ALTER TABLE SCOTT.FS_MENU ADD CONSTRAINT XPKFS_MENU PRIMARY KEY (FSM_CODE); 

