CREATE TABLE SCOTT.FOOD_STORE
(
  FS_CODE       NUMBER(4)                       NOT NULL,
  FS_NAME       VARCHAR2(50 BYTE)               NOT NULL,
  FS_LATITUDE   VARCHAR2(50 BYTE)               NOT NULL,
  FS_LONGITUDE  VARCHAR2(50 BYTE)               NOT NULL,
  FS_SIZE       VARCHAR2(50 BYTE),
  FS_OPENTIME   VARCHAR2(50 BYTE),
  FS_CLOSETIME  VARCHAR2(50 BYTE),
  FS_GOOD       NUMBER(10),
  FS_BAD        NUMBER(10),
  FS_PICTURE    VARCHAR2(100 BYTE),
  FS_JUSO       VARCHAR2(200 BYTE),
  FSM_CODE      NUMBER(4)
);

ALTER TABLE SCOTT.FOOD_STORE ADD (
  CONSTRAINT XPKFOOD_STORE
  PRIMARY KEY
  (FS_CODE));